{
 "title": "DPM-Bench",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Incoming Messages Model Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_messagesin_total{topic=\"model\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Messages Input Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_messagesin_total{topic=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Lag Input Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(consumergroup, topic) (kafka_consumergroup_lag >= 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}